spring:
  security:
    user:
      name: user
      password: pass
      enabled: false
  datasource:
    url: jdbc:mysql://81.69.160.51:3306/test_gradsync
    username: test_gradsync
    password: s8tXp2PHCrGXBwb4
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:backend/mapper/*.xml
    type-aliases-package: backend.model.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secretkey: VHJ1c3R3b3JrT3BhZHVzJTIwU2VjdXJlU2VjcmV0Q29tcGxleEJ0b2xkY29tcGxleENvbmZpZyUyMExhcmdlU2VjcmV0S2V5
  freshTokenExpiration: 2592000000 #30 days
  accessTokenExpiration: 259200000 # 3 days
  token-name: Authorization

  # Private token claims
  uid: uid