server:
  port: 8081
  max-http-request-header-size: 1048576

spring:
  profiles:
    active: dev,rs,pool
  pagehelper:
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true


logging:
  file:
    name: log/log.log
  level:
    root: INFO
    bms.exception: ERROR

