server:
  port: 8081
  max-http-request-header-size: 1048576

spring:
  profiles:
    active: dev,rs,pool,s3
  pagehelper:
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB


logging:
  file:
    name: log/log.log
  level:
    root: INFO
    bms.exception: ERROR

